version: "3.8"

services:
  myapp:
    image: db627/is373-djangoproject:main
    container_name: djangofile
    pull_policy: always
    restart: always
    ports:
      - "8090:8000" 
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "latest"
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  traefik:
    external: true
  backend:
    external: true
